name: Pipeline

on:
  push:
    branches:
      - main
      - gh-actions
  pull_request:
    branches:
      - main
      - gh-actions

jobs:
  run-automated-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Fetch code
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Playwright
      - name: Install Playwright
        run: npx playwright install

      # Run tests
      - name: Run tests
        env:
            TEST_USERNAME: ${{ secrets.TEST_USERNAME}}
            TEST_PASSWORD: ${{ secrets.TEST_PASSWORD}}
        run: npm run run-tests

      # Publish results
      - name: Save test results as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: ./playwright-report
