name: Pipeline

on:
  push:
    branches:
      - main
      - gh-actions
  pull_request:
    branches:
      - main
      - gh-actions

jobs:
  run-automated-tests:
    runs-on: ubuntu-latest

    steps:
        #Checkout
      - name: Fetch code
        uses: actions/checkout@v4

        #Install packages
      - name: Install dependencices
        run: npm install

        #Install playwrighht
      - name: Install Playwright
        run: npx playwright install

        #Run tests
      - name: Run tests
        run: npm run run-tests        

        #Publish Results
      - name: Save test results as artifacts
        uses: actions/upload-artifact@v4
        with:
            name: playwright-test-results
            path: ./playwright-report
